# ===================================================================================================
# SOURCEFILE: module_ids.py
# Relative Path: src/core/module_ids.py
# Purpose: Strong-typed module asset references with nested and flat alias compatibility.
# Call Chain: scripts/manifest_manager.py --export
# Project: BFT_v2
# Team: Ringo / George / John / Paul
# Version: 3.0.4
# Lifecycle: Generated
# Status: Production
# Updated: 2026-09-23 02:48:13Z
# independent_entry_point: false
# ===================================================================================================

# Auto-Generated by: scripts/manifest_manager.py
# Source Manifest: project_manifest.json
# Generated (UTC): 2026-09-23 02:48:13Z
# Hash: 189af2e39503021a61ff1dd1719365e5ee895294972c7c4e04a24d2a3e99c174

from __future__ import annotations

import hashlib
from pathlib import Path

MANIFEST_HASH = "189af2e39503021a61ff1dd1719365e5ee895294972c7c4e04a24d2a3e99c174"
MANIFEST_VERSION = "3.0.4"

# Project root is 2 levels above: src/core/module_ids.py -> src/core -> src -> <root>
PROJECT_ROOT = Path(__file__).resolve().parents[2]

def _sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open('rb') as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b''):
            h.update(chunk)
    return h.hexdigest()

def verify_sync() -> bool:
    """Return True when the current manifest content matches the hash used at generation."""
    try:
        manifest_path = ModuleIDs.Root.ProjectManifest.path()
        current = _sha256_file(manifest_path)
        return current == MANIFEST_HASH
    except Exception:
        return False

class ModuleIDs:
    """Registry of governed code assets."""

    class Root:
        class ProjectManifest:
            LOGICAL_NAME = "ProjectManifest"
            FILE_PATH = ".pyprojectmgr/project_manifest.json"
            UID = "ProjectManifest"
            IMPORT_PATH = None
            @classmethod
            def path(cls) -> Path:
                return PROJECT_ROOT / cls.FILE_PATH

