# ============================================================================
# FILE: test_v115_compat.py - FINAL CORRECTED VERSION
# ============================================================================
import pytest
from pathlib import Path
import sys
import os

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '../../src')))

from core.profiles.plain_marker import PlainMarkerProfile
from core.models import BundleEntry, BundleManifest

@pytest.mark.regression
class TestV115WriteBehavior:
    def test_header_generation_format(self):
        """Test v1.1.5 header format is generated by the PROFILE, not the writer."""
        entry = BundleEntry(
            path='test.py',
            content='content',
            is_binary=False,
            encoding='utf-8',
            eol_style='LF'
        )
        manifest = BundleManifest(entries=[entry], profile='plain_marker')
        profile = PlainMarkerProfile()
        
        # Test the thing that actually makes the bundle text
        bundle_text = profile.format_manifest(manifest)
        
        # v1.1.5 format: # FILE: path with === borders
        assert '# FILE: test.py' in bundle_text
        assert '# ===' in bundle_text
